export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOG_IN = 'LOG_IN';
export const EMAIL_ERROR_OCCURED = 'EMAIL_ERROR_OCCURED';
export const PASSWORD_ERROR_OCCURED = 'PASSWORD_ERROR_OCCURED';
export const ERROR_OCCURED = 'ERROR_OCCURED';
export const IS_LOADING = 'IS_LOADING';


export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE';
export const EMPLOYEE_FETCH_SUCESS ='EMPLOYEE_FETCH_SUCESS'
export const EMPLOYEE_FETCH_FAIL = 'EMPLOYEE_FETCH_FAIL'
export const EMPLOYEE_FETCH_LOADING = 'EMPLOYEE_FETCH_LOADING'
export const EMPLOYEE_SAVED_SUCCESS = 'EMPLOYEE_SAVED_SUCCESS';
